version: '3.8'

services:
  app:
    build: .
    image: auth:latest
    container_name: auth-container
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
