version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    image: auth-app-image
    container_name: auth-app-container
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
